<?php

/**
 * @file
 * Contains notification.module.
 * Hooks & general code for the Acas notifications
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Language\Language;

/**
 * Implements hook_help().
 */
function notification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the general module.
    case 'help.page.general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Acas notification module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter
 */

function notification_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'webform_submission') !== FALSE && strpos($form_id, 'notification') !== FALSE && \Drupal::theme()->getActiveTheme()->getName() == 'acas') {
    $config = \Drupal::config('afd.settings');
    $form['#attached']['library'][] = 'notification/notification_form';
    $form['#attached']['drupalSettings']['afd'] = [
      'serial' => $config->get('serial'),
      'password' => $config->get('password'),
    ];
    if (@$form['actions']['wizard_prev']) {
      $form['back'] = $form['actions']['wizard_prev'];
      $form['back']['#value'] = 'Back';
      $form['back']['#weight'] = -10;
      $form['back']['#attributes']['class'][] = 'back--link';
      unset($form['actions']['wizard_prev']);
    }
    if (@$form['actions']['draft']) {
      $form['actions']['draft']['#attributes']['class'][] = 'btn--secondary';
    }
    if (@$form['actions']['wizard_next']) {
      $form['actions']['wizard_next']['#attributes']['class'][] = 'btn--primary';
    }
    if (@$form['actions']['submit']) {
      $form['actions']['submit']['#attributes']['class'][] = 'btn--primary';
    }
  }
}

/**
 * Implements the EC Entry Switch
 */
function notification_ec_entry_switch() {
  // See if a returning user (ec_entry cookie is set)
  // For testing, can bypass this test by adding ?nc=1 to URL
  if (isset($_COOKIE['ec_entry']) && !\Drupal::request()->query->get('nc')) {
    $query = \Drupal::database()->select('node_field_data', 'nfd');
    $query->join('node__field_destination', 'dest', 'dest.entity_id = nfd.nid');
    $query->fields('dest', ['field_destination_uri']);
    $query->condition('nfd.title', $_COOKIE['ec_entry'], '=');
    $result = $query->execute();
    if ($dest = $result->fetchCol()) {
      $response = new RedirectResponse($dest[0]);
      $response->send();
      return;
    }
  }
  // Set the cookie so a returning user will always be re-directed to their original path
  $cookie = time() . rand(1, 9999);
  setcookie('ec_entry', $cookie, time() + (86400 * 30), '/', '', TRUE);
  if (isset($_SERVER['HTTP_REFERER'])) {
    $referer = $_SERVER['HTTP_REFERER'];
  }else{
    $referer = 'https://' . $_SERVER['HTTP_HOST'];
  }
  // Set the values for the ec_entry node
  $values = array(
    'title' => $cookie,
    'type' => 'ec_entry',
    'language' => Language::LANGCODE_NOT_SPECIFIED,
    'uid' => 0,
    'name' => 'Anonymous',
    'field_referer' => ['uri' => $referer, 'title' => '', 'options' => []],
  );
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('ec_entry_switch.settings');
  $enabled = TRUE;
  $now = time() - strtotime("today");
  $today = date('D');
  // Test if the user should be re-directed to the new form
  if (!$config->get('enabled')) {
    $enabled = FALSE;
  }else if ($config->get('current_in_count') >= $config->get('in_count') || $config->get('current_out_count') >= $config->get('out_count')) {
    $enabled = FALSE;
  }else if ($config->get('start_time') && $config->get('end_time') && ($now < $config->get('start_time') || $now > $config->get('end_time'))) {
    $enabled = FALSE;
  }else if ($config->get('weekend') && ($today == 'Sat' || $today == 'Sun')) {
    $enabled = FALSE;
  }
  if (!$enabled) {
    // Re-direct to the old form
    $values['field_destination'] = ['uri' => $config->get('old_url'), 'title' => '', 'options' => []];
    $node = \Drupal::entityTypeManager()->getStorage('node')->create($values);
    $node->save();
    $response = new RedirectResponse($config->get('old_url'));
  }else{
    // Re-direct to the new form
    $values['field_destination'] = ['uri' => $config->get('new_url'), 'title' => '', 'options' => []];
    $node = \Drupal::entityTypeManager()->getStorage('node')->create($values);
    $node->save();
    // Update the in count
    $config->set('current_in_count', $config->get('current_in_count') + 1);
    $config->save();
    $response = new RedirectResponse($config->get('new_url'));
  }
  // Send the re-direct response
  $response->send();
}

function notification_cron() {
  $hour = (int)date('H');
  if ($hour >= 3 && $hour <= 5) {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('ec_entry_switch.settings');
    $config->set('current_in_count', 0);
    $config->set('current_out_count', 0);
    $config->save();
    \Drupal::logger('notification')->notice('CRON cleared current counts');
  }
}

function notification_company_house($employer) {
  $config = \Drupal::config('companies_house.settings');
  $api = new companiesHouseApi($config->get('api'));
  $response = $api->send('/search/companies', ['q' => $employer]);
  $return = [];
  foreach($response['items'] as $item) {
    if ($item['company_status'] == 'active') {
      $return[] = $item;
    }
  }
  return $return;
}

function notification_confirmation($webform, $webform_submission_id) {
  if (strpos($webform, 'notification') !== FALSE) {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('ec_entry_switch.settings');
    $config->set('current_out_count', $config->get('current_out_count') + 1);
    $config->save();
    $query = \Drupal::database()->select('node_field_data', 'nfd');
    $query->fields('nfd', ['nid']);
    $query->condition('nfd.title', @$_COOKIE['ec_entry'], '=');
    $result = $query->execute();
    if ($nid = $result->fetchCol()) {
      $node = \Drupal\node\Entity\Node::load($nid[0]);
      $node->field_end->value = date('Y-m-d\TH:i:s', time() - date('Z'));
      $node->save();
    }
    $ref = notification_build_reference_number();
    if (notification_send_dynamics($webform_submission_id, $ref)) {
      
    }
    /*
    $config = \Drupal::config('dynamics.settings');
    $client = \AlexaCRM\WebAPI\ClientFactory::createOnlineClient(
      $config->get('organization_uri'),
      $config->get('application_id'),
      $config->get('application_secret')
    );
    $entities = [
      'contact' => new \AlexaCRM\Xrm\Entity('contact'),
      'account' => new \AlexaCRM\Xrm\Entity('account'),
      'representative' => new \AlexaCRM\Xrm\Entity('contact'),
      'employer' => new \AlexaCRM\Xrm\Entity('contact'),
      'case' => new \AlexaCRM\Xrm\Entity('incident'),
    ];
    foreach($data as $field => $value) {
      notification_build_field($entities, $field, $value);
    }
    $accountId = $client->Create($entities['account']);
    $contactId = $client->Create($entities['contact']);
    $associate = [new \AlexaCRM\Xrm\EntityReference( 'contact', $contactId )];
    if (@$entities['representative']['statuscode']) {
      $representativeId = $client->Create($entities['representative']);
      $associate[] = new \AlexaCRM\Xrm\EntityReference( 'contact', $representativeId );
    }
    if (@$entities['employer']['statuscode']) {
      $employerId = $client->Create($entities['employer']);
      $associate[] = new \AlexaCRM\Xrm\EntityReference( 'contact', $employerId );
    }
    $entities['case']['title'] = $entities['contact']['firstname'] . ' ' . $entities['contact']['lastname'];
    $entities['case']['customerid'] = new AlexaCRM\Xrm\EntityReference( 'account', $accountId );
    $entities['case']['ticketnumber'] = $ref;
    $caseId = $client->Create($entities['case']);
    $client->Associate(
      'account',
      $accountId,
      new \AlexaCRM\Xrm\Relationship( 'contact_customer_accounts' ), $associate
    );
    */
  }
  $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
  $node = \Drupal\node\Entity\Node::load(94);
  $view = $view_builder->view($node, 'full');
  $html = drupal_render($view);
  $html = str_replace('[REFERENCE]', $ref, $html);
  $html = str_replace('[DATE]', date('h:i A \o\n d F Y'), $html);
  if ($data['is_this_employer_still_trading'] == 'No') {
    $html = str_replace('[SPECIFIC GUIDANCE]', 'You told us that your employer has ceased trading. You can <a href="https://www.gov.uk/your-rights-if-your-employer-is-insolvent" target="_blank">find out what rights you have as the employee of an insolvent employer on GOV.UK.</a>', $html);
  }else{
    $html = str_replace('[SPECIFIC GUIDANCE]', '', $html);
  }
  $a = explode('</h2>', $html, 2);
  $b = explode('<h2>', $a[0]);
  $html = $b[0] . '<h1 class="thank-you-page-header">Thank you!</h1>' . $a[1];
  return $html;
}

function notification_send_dynamics($webform_submission_id, $ref = 'TEST') {
  $webform_submission = WebformSubmission::load($webform_submission_id);
  $data = $webform_submission->getData();
  $json = [];
  $incident_type = [];
  $info = '';
  foreach($data as $key => $value) {
    if (is_string($value) && strpos($key, 'acas_') !== FALSE) {
      $json[$key] = $value;
    }else if (is_array($value) && strpos($key, '_address') !== FALSE) {
      if ($key == 'claimant_address') {
        $json['acas_addressline1'] = $value['address'];
        $json['acas_addressline2'] = $value['address_2'];
        $json['acas_citytown'] = $value['city'];
        $json['acas_postcode'] = $value['postal_code'];
      }else if ($key == 'representative_address') {
        $json['acas_claimrepaddressline1'] = $value['address'];
        $json['acas_claimrepaddressline2'] = $value['address_2'];
        $json['acas_claimrepcitytown'] = $value['city'];
        $json['acas_claimreppostcode'] = $value['postal_code'];
      }else if ($key == 'respondant_address') {
        $json['acas_respaddressline1'] = $value['address'];
        $json['acas_respaddressline2'] = $value['address_2'];
        $json['acas_respcitytown'] = $value['city'];
        $json['acas_resppostcode'] = $value['postal_code'];
      }
    }
    if ($key == 'do_you_believe_that_you_have_been_discriminated_against' && $value) {
      $incident_type[] = '602700003';
    }
    if ($key == 'do_you_think_you_are_owed_holiday_by_your_employer' && $value) {
      $incident_type[] = '602700001';
    }
    if ($key == 'do_you_think_you_are_owed_wages' && $value) {
      $incident_type[] = '602700000';
    }
    if ($key == 'do_you_believe_you_have_been_unfairly_dismissed_or_made_redundan' && $value) {
      if ($value == 2) {
        // unfairly dismissed
        $incident_type[] = '602700002';
      }else if ($value == 3) {
        // made redundant
        $incident_type[] = '602700004';
      }
    }
    if ($key == 'are_you_currently_unemployed_' && $value == 'Yes') {
      $info .= "Claimant is currently unemployed.\n";
    }
    if ($key == 'did_you_have_a_meeting_with_your_employer_before_you_were_dismis' && $value) {
      if ($value == 'Yes') {
        $h = 'has';
      }else{
        $h = 'has not';
      }
      $info .= "Claimant $h had a meeting with their employer before they were dismissed.\n";
    }
    if ($key == 'did_you_have_meet_with_your_employer_after_you_were_dismissed_' && $value) {
      if ($value == 'Yes') {
        $h = 'has';
      }else{
        $h = 'has not';
      }
      $info .= "Claimant $h had a meeting with their employer after they were dismissed.\n";
    }
    if ($key == 'did_your_emplyer_given_any_explanation_optional_' && $value) {
      $info .= "Employer explanation: $value\n";
    }
    if ($key == 'do_you_know_what_you_want_as_an_outcome_' && $value) {
      $info .= "Claimant wants: $value\n";
    }
    if ($key == 'do_you_know_what_you_want_as_an_outcome_2' && $value) {
      $info .= "Claimant wants: $value\n";
    }
    if ($key == 'do_you_know_what_you_want_as_an_outcome_3' && $value) {
      $info .= "Claimant wants: $value\n";
    }
    if ($key == 'explain_why_you_think_you_are_owed_wages_optional_' && $value) {
      $info .= "Claimant believes they are owed money: $value\n";
    }
    if ($key == 'have_you_told_your_employer_and_asked_them_to_rectify_the_proble' && $value) {
      if ($value == 'Yes') {
        $h = 'has';
      }else{
        $h = 'has not';
      }
      $info .= "Claimant $h asked the employer for this money.\n";
    }
    if ($key == 'how_much_holiday_do_you_think_you_are_owed' && $value) {
      $info .= "$value holiday days are in dispute.\n";
    }
    if ($key == 'i_belive_that_my_employer_has_discriminated_against_me_because_' && $value) {
      $r = implode(', ', $value);
      $info .= "Claimant is claiming $r discrimination.\n";
    }
    
    
    if ($key == 'is_this_employer_still_trading' && $value == 'No') {
      $info .= "Claimant believes employer is insolvent.\n";
    }
    if ($key == 'have_you_been_employed_by_this_employer_for_a_2_years_or_more_' && $value == 'No') {
      $info .= "Claimant has NOT worked for 2 years or more for this employer.\n";
    }
    if ($key == 'have_you_been_employed_by_this_employer_for_a_2_years_or_more_' && $value == 'Yes') {
      $info .= "Claimant has worked for 2 years or more for this employer.\n";
    }
    if ($key == 'when_were_you_dismissed' && $value && $value['day'] && $value['month'] && $value['year']) {
      $date = $value['year'] . '/' . str_pad($value['month'], 2, '0', STR_PAD_LEFT) . '/' . str_pad($value['day'], 2, '0', STR_PAD_LEFT);
      $json['acas_incidentdate'] = $date;
      $info .= 'Claimants last day of work was ' . $date . "\n";
    }
  }
  $json['acas_incidentinfo'] = $info;
  if ($incident_type) {
    $json['acas_incidenttype'] = implode(',', $incident_type);
  }
  $json['acas_respondenttype'] = '602700001'; // Personal
  // Now send the data
  $data_string = json_encode(['notification' => $json]);
  die($data_string);
  $ch = curl_init('https://dev-tell.acas.org.uk/notify-test');                                                                      
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");                                                                     
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);                                                                  
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);                                                                      
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(                                                                          
    'Content-Type: application/json',                                                                                
    'Content-Length: ' . strlen($data_string))                                                                       
  );                                                                                                                   
  $result = curl_exec($ch);
  $http_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
}

function notification_build_field(&$entities, $field, $data) {
  $a = explode('-', $field);
  if (!isset($entities[$a[0]])) {
    return;
  }
  if ($data) {
    $entities[$a[0]]['statecode'] = 0;
    $entities[$a[0]]['statuscode'] = 1;
    if ($a[1] == 'address') {
      $entities[$a[0]]['address1_line1'] = trim($data['address']);
      $entities[$a[0]]['address1_line2'] = trim($data['address_2']);
      $entities[$a[0]]['address1_city'] = trim($data['city']);
      $entities[$a[0]]['address1_postalcode'] = trim($data['postal_code']);
    }else{
      if (is_string($data)) {
        $entities[$a[0]][$a[1]] = trim($data);
      }else{
        $entities[$a[0]][$a[1]] = implode(',', $data);
      }
    }
  }
}

function notification_build_reference_number() {
  $ref = str_pad(rand(20000, 99999), 8, '0', STR_PAD_LEFT);
  $sub = rand(10, 99);
  return $ref . '/' . $sub;
}

final class companiesHouseApi {
  const API_ENDPOINT = 'https://api.companieshouse.gov.uk';
  private $api_key = null;
  /**
   * @param $api_key
   */
  public function __construct($api_key) {
    if (!empty($api_key)) {
      $this->api_key = $api_key;
    } else {
      throw new InvalidArgumentException('Please supply a valid API key');
    }
  }
  /**
   * @param string $endpoint
   * @param array  $payload
   *
   * @return mixed
   */
  public function send($endpoint, array $payload = []) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $this->getRequestUrl($endpoint, $payload));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, $this->api_key . ':');
    $result = curl_exec($ch);
    curl_close($ch);
    if ($json = json_decode($result, true)) {
      $result = $json;
    }
    return $result;
  }
  /**
   * @param string $endpoint
   * @param array  $payload
   *
   * @return string
   */
  private function getRequestUrl($endpoint, array $payload) {
    $payload = array_merge($payload, ['ts' => time()]);
    $qs = '?' . http_build_query($payload);
    return self::API_ENDPOINT . $endpoint . $qs;
  }
}