<?php

/**
 * @file
 * Contains notification.module.
 * Hooks & general code for the Acas notifications
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Language\Language;

/**
 * Implements hook_help().
 */
function notification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the general module.
    case 'help.page.general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Acas notification module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view().
 */
function notification_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'full' && $entity instanceof \Drupal\node\NodeInterface && $entity->getType() == 'secondary_page') {
    if (isset($_COOKIE['webform_preview'])) {
      unset($_COOKIE['webform_preview']);
      setcookie('webform_preview', null, -1, '/');
    }
  }
}

/**
 * Implements hook_webform_submission_form_alter
 */
function notification_webform_submission_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['elements']['form_type']['#value'])) {
    // Either a Notification or Conciliation form
    /*
    if ($form_id == 'webform_submission_notification_dispute_start_add_form') {
      // Test with Dynamics if details have already been submitted
      $response = new RedirectResponse('/you-have-already-submitted-your-details-to-acas');
      $response->send();
      return;
    }
    */
    // is valid to show this form
    if ($form['elements']['form_type']['#value'] == 'Notification' && isset($_COOKIE['acas_eccaserefnumber'])) {
      // Notification form already completed. Goto Conciliation form
      $response = new RedirectResponse('/start-conciliation');
      $response->send();
      return;
    }else if ($form['elements']['form_type']['#value'] == 'Conciliation') {
      if (!$acas_eccaserefnumber = \Drupal::request()->query->get('acas_eccaserefnumber')) {
        $acas_eccaserefnumber = @$_COOKIE['acas_eccaserefnumber'];
      }
      if ($acas_eccaserefnumber) {
        $query = \Drupal::database()->select('acas_ecrefno', 'a');
        $query->fields('a', array('status', 'timestamp'));
        $query->condition('a.reference_no', $acas_eccaserefnumber, '=');
        $result = $query->execute();
        if($status = $result->fetch()) {
          if ($status->status) {
            // Have already completed this form
            $path = Drupal\Core\URL::fromUserInput('/already-submitted', array('query' => array('ref' => $acas_eccaserefnumber, 'date' => $status->timestamp)))->toString();
            $response = new RedirectResponse($path);
            $response->send();
            return;
          }
        }
      }
    }
    $config = \Drupal::config('afd.settings');
    $form['#attached']['library'][] = 'notification/notification_form';
    $form['#attached']['drupalSettings']['afd'] = [
      'url' => $config->get('url'),
      'token' => $config->get('token'),
    ];
    if (@$form['actions']['wizard_prev']) {
      if (!@$_COOKIE['webform_preview']) {
        $form['back'] = $form['actions']['wizard_prev'];
        $form['back']['#value'] = 'Back';
        $form['back']['#weight'] = -10;
        $form['back']['#attributes']['class'][] = 'back--link';
      }
      unset($form['actions']['wizard_prev']);
    }
    if (@$form['actions']['preview_prev']) {
      unset($form['actions']['preview_prev']);
    }
    if (@$form['actions']['draft']) {
      $form['actions']['draft']['#attributes']['class'][] = 'btn-secondary';
    }
    if (@$form['actions']['wizard_next']) {
      $form['actions']['wizard_next']['#attributes']['class'][] = 'btn-primary';
    }
    if (@$form['actions']['submit']) {
      $form['actions']['submit']['#attributes']['class'][] = 'btn-primary';
    }
    $element_key = $form_state->getTriggeringElement();
    //if ($element_key && strpos($element_key['#id'], 'edit-actions-wizard-next') !== FALSE) {
      if (@$_COOKIE['webform_preview']) {
        $pages = $form_state->get('pages');
        $all_keys = array_keys($pages);
        $goto_destination_page_index = array_search('webform_preview', $all_keys);
        if($goto_destination_page_index > 0){
          $form_state->set('current_page', $all_keys[$goto_destination_page_index -1]);
        }
      }else {
        $current_page = $form_state->get('current_page');
        if ($current_page == 'webform_preview') {
          setcookie('webform_preview', '1', NULL, '/');
        }
      }
    //}
    if ($element_key && strpos($element_key['#id'], 'edit-actions-preview-next') !== FALSE) {
      setcookie('webform_preview', '1', NULL, '/');
    }
    if ($acas_eccaserefnumber = \Drupal::request()->query->get('acas_eccaserefnumber')) {
      setcookie('acas_eccaserefnumber', $acas_eccaserefnumber, time() + 2592000, '/');
    }
  }
}

/**
 * Implements the EC Entry Switch
 */
function notification_ec_entry_switch() {
  // See if a returning user (ec_entry cookie is set)
  // For testing, can bypass this test by adding ?nc=1 to URL
  if (isset($_COOKIE['ec_entry']) && !\Drupal::request()->query->get('nc')) {
    $query = \Drupal::database()->select('node_field_data', 'nfd');
    $query->join('node__field_destination', 'dest', 'dest.entity_id = nfd.nid');
    $query->fields('dest', ['field_destination_uri']);
    $query->condition('nfd.title', $_COOKIE['ec_entry'], '=');
    $result = $query->execute();
    if ($dest = $result->fetchCol()) {
      $response = new RedirectResponse($dest[0]);
      $response->send();
      return;
    }
  }
  // Set the cookie so a returning user will always be re-directed to their original path
  $cookie = time() . rand(1, 9999);
  setcookie('ec_entry', $cookie, time() + (86400 * 30), '/', '', TRUE);
  if (isset($_SERVER['HTTP_REFERER'])) {
    $referer = $_SERVER['HTTP_REFERER'];
  }else{
    $referer = 'https://' . $_SERVER['HTTP_HOST'];
  }
  // Load service to detect if a mobile
  $mobileDetector = \Drupal::service('mobile_detect');
  // Set the values for the ec_entry node
  $values = array(
    'title' => $cookie,
    'type' => 'ec_entry',
    'language' => Language::LANGCODE_NOT_SPECIFIED,
    'uid' => 0,
    'name' => 'Anonymous',
    'field_mobile' => $mobileDetector->isMobile(),
    'field_referer' => ['uri' => $referer, 'title' => '', 'options' => []],
  );
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('ec_entry_switch.settings');
  $enabled = TRUE;
  $now = time() - strtotime("today");
  $today = date('D');
  // Test if the user should be re-directed to the new form
  if (!$config->get('enabled')) {
    $enabled = FALSE;
  }else if ($config->get('current_in_count') >= $config->get('in_count') || $config->get('current_out_count') >= $config->get('out_count')) {
    $enabled = FALSE;
  }else if ($config->get('start_time') && $config->get('end_time') && ($now < $config->get('start_time') || $now > $config->get('end_time'))) {
    $enabled = FALSE;
  }else if ($config->get('weekend') && ($today == 'Sat' || $today == 'Sun')) {
    $enabled = FALSE;
  }
  if (!$enabled) {
    // Re-direct to the old form
    $url = $config->get('old_url');
    if ($mobileDetector->isMobile()) {
      $url = str_replace('www.', 'm.', $url);
    }
    $values['field_destination'] = ['uri' => $url, 'title' => '', 'options' => []];
    $node = \Drupal::entityTypeManager()->getStorage('node')->create($values);
    $node->save();
    $response = new RedirectResponse($url);
  }else{
    // Re-direct to the new form
    $values['field_destination'] = ['uri' => $config->get('new_url'), 'title' => '', 'options' => []];
    $node = \Drupal::entityTypeManager()->getStorage('node')->create($values);
    $node->save();
    // Update the in count
    $config->set('current_in_count', $config->get('current_in_count') + 1);
    $config->save();
    $response = new RedirectResponse($config->get('new_url'));
  }
  // Send the re-direct response
  $response->send();
}

function notification_cron() {
  $hour = (int)date('H');
  if ($hour >= 3 && $hour <= 7) {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('ec_entry_switch.settings');
    if ($config->get('current_in_count') || $config->get('current_out_count')) {
      $config->set('current_in_count', 0)->set('current_out_count', 0)->save();
      \Drupal::logger('notification')->notice('Cleared current counts.');
    }
  }
}

function notification_company_house($employer) {
  $config = \Drupal::config('companies_house.settings');
  $api = new companiesHouseApi($config->get('api'));
  $response = $api->send('/search/companies', ['q' => $employer]);
  $return = [];
  foreach($response['items'] as $item) {
    if ($item['company_status'] == 'active') {
      $return[] = $item;
    }
  }
  return $return;
}

function notification_confirmation($webform, $webform_submission_id) {
  $webform_submission = WebformSubmission::load($webform_submission_id);
  $data = $webform_submission->getData();
  drupal_get_messages();
  if ($data['form_type'] == 'Notification') {
    $ref = notification_build_reference_number();
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('ec_entry_switch.settings');
    $config->set('current_out_count', $config->get('current_out_count') + 1);
    $config->save();
    $query = \Drupal::database()->select('node_field_data', 'nfd');
    $query->fields('nfd', ['nid']);
    $query->condition('nfd.title', @$_COOKIE['ec_entry'], '=');
    $result = $query->execute();
    if ($nid = $result->fetchCol()) {
      $node = \Drupal\node\Entity\Node::load($nid[0]);
      $node->field_end->value = date('Y-m-d\TH:i:s', time() - date('Z'));
      $node->save();
    }
    setcookie('acas_eccaserefnumber', $ref, time() + 2592000, '/');
    $db = \Drupal::database();
    $fields = ['reference_no' => $ref];
    $db->insert('acas_ecrefno')
      ->fields($fields)
      ->execute();
    if ($data['are_you_interested_in_settling_your_case_before_tribunal_'] == 'Yes' || $data['are_you_interested_in_settling_your_case_before_tribunal_'] == 1 || !$data['are_you_interested_in_settling_your_case_before_tribunal_']) {
      notification_send_dynamics($webform_submission_id, $ref); // No email
      if (isset($_COOKIE['webform_preview'])) {
        unset($_COOKIE['webform_preview']);
        setcookie('webform_preview', null, -1, '/');
      }
      $response = new RedirectResponse('/start-conciliation?acas_eccaserefnumber=' . $ref);
      $response->send();
      return;
    }else{
      $nid = 114;
      $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
      if (!$node = \Drupal\node\Entity\Node::load($nid)) {
        $node = \Drupal\node\Entity\Node::load(94);
      }
      if ($node->hasField('field_subject')) {
        $email = [
          'subject' => $node->field_subject->getString(),
          'message' => str_replace('[DATE]', date('h:i A \o\n d F Y'), str_replace('[REFERENCE]', $ref, $node->field_message->getString())),
        ];
      }
      notification_send_dynamics($webform_submission_id, $ref, $email);
      notification_send($data, $ref);
      $view = $view_builder->view($node, 'full');
      $html = drupal_render($view);
      $html = str_replace('[REFERENCE]', $ref, $html);
      $html = str_replace('[DATE]', date('h:i A \o\n d F Y'), $html);
      if (@$data['is_this_employer_still_trading'] == 'No') {
        $html = str_replace('[SPECIFIC GUIDANCE]', 'You told us that your employer has ceased trading. You can <a href="https://www.gov.uk/your-rights-if-your-employer-is-insolvent" target="_blank">find out what rights you have as the employee of an insolvent employer on GOV.UK.</a>', $html);
      }else{
        $html = str_replace('[SPECIFIC GUIDANCE]', '', $html);
      }
      $html = '<header id="block-acas-page-title left" class="contextual-region block block-core block-page-title-block clearfix col-xs-12 col-md-7"><h1 class="thank-you-page-header">' . $node->getTitle() . '</h1></header>' . $html;
      return $html;
    }
  }else if ($data['form_type'] == 'Conciliation') {
    $data['acas_eccaserefnumber'] = $_COOKIE['acas_eccaserefnumber'];
    notification_send_dynamics($webform_submission_id, $data['acas_eccaserefnumber']);
    $db = \Drupal::database();
    $db->update('acas_ecrefno')
      ->fields(['status' => 1])
      ->condition('reference_no', $data['acas_eccaserefnumber'], '=')
      ->execute();
    $nid = 114;
    $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
    if (!$node = \Drupal\node\Entity\Node::load($nid)) {
      $node = \Drupal\node\Entity\Node::load(94);
    }
    $view = $view_builder->view($node, 'full');
    $html = drupal_render($view);
    $html = str_replace('[REFERENCE]', $data['acas_eccaserefnumber'], $html);
    $html = str_replace('[DATE]', date('h:i A \o\n d F Y'), $html);
    if (@$data['is_this_employer_still_trading'] == 'No') {
      $html = str_replace('[SPECIFIC GUIDANCE]', 'You told us that your employer has ceased trading. You can <a href="https://www.gov.uk/your-rights-if-your-employer-is-insolvent" target="_blank">find out what rights you have as the employee of an insolvent employer on GOV.UK.</a>', $html);
    }else{
      $html = str_replace('[SPECIFIC GUIDANCE]', '', $html);
    }
    $html = '<header id="block-acas-page-title left" class="contextual-region block block-core block-page-title-block clearfix col-xs-12 col-md-7"><h1 class="thank-you-page-header">' . $node->getTitle() . '</h1></header>' . $html;
    return $html;
  }
}

function notification_send_dynamics($webform_submission_id, $ref = '', $email = NULL) {
  $webform_submission = WebformSubmission::load($webform_submission_id);
  $data = $webform_submission->getData();
  $json = [];
  $json['form_type'] = $data['form_type'];
  $incident_type = [];
  $info = '';
  foreach($data as $key => $value) {
    if (is_string($value) && strpos($key, 'acas_') !== FALSE) {
      $json[$key] = $value;
    }else if (is_array($value) && strpos($key, '_address') !== FALSE) {
      if ($key == 'claimant_address') {
        $json['acas_addressline1'] = $value['address'];
        $json['acas_addressline2'] = $value['address_2'];
        $json['acas_citytown'] = $value['city'];
        $json['acas_postcode'] = $value['postal_code'];
      }else if ($key == 'representative_address') {
        $json['acas_claimrepaddressline1'] = $value['address'];
        $json['acas_claimrepaddressline2'] = $value['address_2'];
        $json['acas_claimrepcitytown'] = $value['city'];
        $json['acas_claimreppostcode'] = $value['postal_code'];
      }else if ($key == 'respondant_address') {
        $json['acas_respaddressline1'] = $value['address'];
        $json['acas_respaddressline2'] = $value['address_2'];
        $json['acas_respcitytown'] = $value['city'];
        $json['acas_resppostcode'] = $value['postal_code'];
      }
    }else if (is_array($value) && @$value['phone']) {
      $json[$key] = $value['phone'];
      if ($value['ext']) {
        $json[$key] .= ';' . $value['ext'];
      }
    }
    if ($key == 'do_you_believe_that_you_have_been_discriminated_against' && $value) {
      $incident_type[] = '602700003';
      unset($data[$key]);
    }
    if ($key == 'do_you_think_you_are_owed_holiday_by_your_employer' && $value) {
      $incident_type[] = '602700001';
      unset($data[$key]);
    }
    if ($key == 'do_you_think_you_are_owed_wages' && $value) {
      $incident_type[] = '602700000';
      unset($data[$key]);
    }
    if ($key == 'do_you_believe_you_have_been_unfairly_dismissed_or_made_redundan' && $value) {
      if ($value == 2) {
        // unfairly dismissed
        $incident_type[] = '602700002';
      }else if ($value == 3) {
        // made redundant
        $incident_type[] = '602700004';
      }
      unset($data[$key]);
    }
    if ($key == 'are_you_currently_unemployed_' && $value == 'Yes') {
      $info .= "Claimant is currently unemployed.\n";
      unset($data[$key]);
    }
    if ($key == 'did_you_have_a_meeting_with_your_employer_before_you_were_dismis' && $value) {
      if ($value == 'Yes') {
        $h = 'has';
      }else{
        $h = 'has not';
      }
      $info .= "Claimant $h had a meeting with their employer before they were dismissed.\n";
      unset($data[$key]);
    }
    if ($key == 'did_you_meet_with_your_employer_after_you_were_dismissed_' && $value) {
      if ($value == 'Yes') {
        $h = 'has';
      }else{
        $h = 'has not';
      }
      $info .= "Claimant $h had a meeting with their employer after they were dismissed.\n";
      unset($data[$key]);
    }
    if ($key == 'please_give_us_a_brief_explanation_about_your_claim' && $value) {
      $info .= $value . "\n";
    }
    if ($key == 'did_your_employer_given_any_explanation_optional_' && $value) {
      $info .= "Employer explanation: $value\n";
      unset($data[$key]);
    }
    if ($key == 'do_you_know_what_you_want_as_an_outcome_' && $value) {
      $info .= "Claimant wants: $value\n";
      unset($data[$key]);
    }
    if ($key == 'do_you_know_what_you_want_as_an_outcome_2' && $value) {
      $info .= "Claimant wants: $value\n";
      unset($data[$key]);
    }
    if ($key == 'do_you_know_what_you_want_as_an_outcome_3' && $value) {
      $info .= "Claimant wants: $value\n";
      unset($data[$key]);
    }
    if ($key == 'explain_why_you_think_you_are_owed_wages_optional_' && $value) {
      $info .= "Claimant believes they are owed money: $value\n";
      unset($data[$key]);
    }
    if ($key == 'have_you_told_your_employer_and_asked_them_to_rectify_the_proble' && $value) {
      if ($value == 'Yes') {
        $h = 'has';
      }else{
        $h = 'has not';
      }
      $info .= "Claimant $h asked the employer for this money.\n";
      unset($data[$key]);
    }
    if ($key == 'how_much_holiday_do_you_think_you_are_owed' && $value) {
      $info .= "$value holiday days are in dispute.\n";
      unset($data[$key]);
    }
    if ($key == 'i_believe_that_my_employer_has_discriminated_against_me_because_' && $value) {
      $r = implode(', ', $value);
      $info .= "Claimant is claiming $r discrimination.\n";
      unset($data[$key]);
    }
    if ($key == 'is_this_employer_still_trading' && $value == 'No') {
      $info .= "Claimant believes employer is insolvent.\n";
      unset($data[$key]);
    }
    if ($key == 'have_you_been_employed_by_this_employer_for_a_2_years_or_more_' && $value == 'No') {
      $info .= "Claimant has NOT worked for 2 years or more for this employer.\n";
      unset($data[$key]);
    }
    if ($key == 'have_you_been_employed_by_this_employer_for_a_2_years_or_more_' && $value == 'Yes') {
      $info .= "Claimant has worked for 2 years or more for this employer.\n";
      unset($data[$key]);
    }
    if ($key == 'when_were_you_dismissed' && $value && $value['day'] && $value['month'] && $value['year']) {
      $date = $value['year'] . '-' . str_pad($value['month'], 2, '0', STR_PAD_LEFT) . '-' . str_pad($value['day'], 2, '0', STR_PAD_LEFT);
      $json['acas_incidentdate'] = $date;
      $info .= 'Claimants last day of work was ' . $date . "\n";
      unset($data[$key]);
    }
    if ($key == 'when_were_you_made_redundant_optional_' && $value && $value['day'] && $value['month'] && $value['year']) {
      $date = $value['year'] . '-' . str_pad($value['month'], 2, '0', STR_PAD_LEFT) . '-' . str_pad($value['day'], 2, '0', STR_PAD_LEFT);
      $info .= 'Claimant believes they were made redundant on ' . $date . "\n";
      unset($data[$key]);
    }
    if ($key == 'when_were_you_not_paid_properly_optional_' && $value && $value['day'] && $value['month'] && $value['year']) {
      $date = $value['year'] . '-' . str_pad($value['month'], 2, '0', STR_PAD_LEFT) . '-' . str_pad($value['day'], 2, '0', STR_PAD_LEFT);
      $info .= 'Claimant believes they were made redundant on ' . $date . "\n";
      unset($data[$key]);
    }
  }
  
  $json['acas_incidentinfo'] = $info;
  if ($incident_type) {
    $json['acas_incidenttype'] = implode(',', $incident_type);
  }
  $json['acas_respondenttype'] = '602700001'; // Personal
  $json['acas_eccaserefnumber'] = $ref;
  if (!@$json['acas_incidenttype']) {
    $json['acas_incidenttype'] = '602700000';
  }
  if ($email) {
    $json['acas_email'] = $email;
  }
  // Now send the data
  $data_string = json_encode($json);
  $config = \Drupal::config('dynamics.settings');
  $ch = curl_init($config->get('url') . '?si_token=' . $config->get('token'));                                                                      
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");                                                                     
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);                                                                  
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);                                                                      
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(                                                                          
    'Content-Type: application/json',                                                                                
    'Content-Length: ' . strlen($data_string))                                                                       
  );                                                                                                                   
  $result = curl_exec($ch);
  $http_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
  if ($result || $http_status != 200) {
    \Drupal::logger('Dynamics')->notice('Status = ' . $http_status . '<br /> JSON = ' . $data_string . '<hr><br /> Result = ' . $result);
  }
}

function notification_send($data, $ref) {
  return;
  $config = \Drupal::config('gov_notify.settings');
  if ($data['acas_emailaddress']) {
    $notifyClient = new \Alphagov\Notifications\Client([
      'apiKey' => $config->get('key'),
      'httpClient' => new \Http\Adapter\Guzzle6\Client
    ]);
    try {
      $response = $notifyClient->sendEmail(
        $data['acas_emailaddress'],
        '3f2000f6-9e74-4816-ad53-829bc133c422', [
            'first_name' => $data['acas_firstname'],
            'reference'  => $ref,
            'date' => date('h:i A \o\n d F Y'),
        ],
          '',
          NULL
        );
    } catch (NotifyException $e){
      
    }
  }
}

function notification_build_field(&$entities, $field, $data) {
  $a = explode('-', $field);
  if (!isset($entities[$a[0]])) {
    return;
  }
  if ($data) {
    $entities[$a[0]]['statecode'] = 0;
    $entities[$a[0]]['statuscode'] = 1;
    if ($a[1] == 'address') {
      $entities[$a[0]]['address1_line1'] = trim($data['address']);
      $entities[$a[0]]['address1_line2'] = trim($data['address_2']);
      $entities[$a[0]]['address1_city'] = trim($data['city']);
      $entities[$a[0]]['address1_postalcode'] = trim($data['postal_code']);
    }else{
      if (is_string($data)) {
        $entities[$a[0]][$a[1]] = trim($data);
      }else{
        $entities[$a[0]][$a[1]] = implode(',', $data);
      }
    }
  }
}

function notification_build_reference_number() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('acas.settings');
  $ref = $config->get('notification_ref_no');
  $config->set('notification_ref_no', $ref + 1);
  $config->save();
  return 'R' . $ref .  '/' . date('y');
}


final class companiesHouseApi {
  const API_ENDPOINT = 'https://api.companieshouse.gov.uk';
  private $api_key = null;
  /**
   * @param $api_key
   */
  public function __construct($api_key) {
    if (!empty($api_key)) {
      $this->api_key = $api_key;
    } else {
      throw new InvalidArgumentException('Please supply a valid API key');
    }
  }
  /**
   * @param string $endpoint
   * @param array  $payload
   *
   * @return mixed
   */
  public function send($endpoint, array $payload = []) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $this->getRequestUrl($endpoint, $payload));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, $this->api_key . ':');
    $result = curl_exec($ch);
    curl_close($ch);
    if ($json = json_decode($result, true)) {
      $result = $json;
    }
    return $result;
  }
  /**
   * @param string $endpoint
   * @param array  $payload
   *
   * @return string
   */
  private function getRequestUrl($endpoint, array $payload) {
    $payload = array_merge($payload, ['ts' => time()]);
    $qs = '?' . http_build_query($payload);
    return self::API_ENDPOINT . $endpoint . $qs;
  }
}